package com.master_hesso.smartcantonmanager.utils;

import java.util.UUID;

public class SmartCantonDevBoxBLEServices {

    /* SMARTCANTON_DEVBOX_LORA_SERVICE */
    public static final UUID SMARTCANTON_DEVBOX_LORA_SERVICE =
            UUID.fromString("00000000-AAAA-BBBB-CCCC-DDDDDDDDDDDD");

    public static final UUID SMARTCANTON_DEVBOX_LORA_APP_EUI =
            UUID.fromString("00000001-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_LORA_APP_KEY =
            UUID.fromString("00000002-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_LORA_DEVICE_EUI =
            UUID.fromString("00000003-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_LORA_LORA_CONFIRM_MODE =
            UUID.fromString("00000004-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_LORA_NETWORK_JOIN_STATUS =
            UUID.fromString("00000005-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_LORA_NETWORK_DEVICE_ADDRESS =
            UUID.fromString("00000006-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_LORA_NETWORK_NWTORK_SESSION_KEY =
            UUID.fromString("00000007-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_LORA_NETWORK_APP_SESSION_KEY =
            UUID.fromString("00000008-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_LORA_NETWORK_VALIDATE_NEW_CONFIGURATION =
            UUID.fromString("00000009-AAAA-BBBB-CCCC-DDDDDDDDDDDD");

    /* SMARTCANTON_DEVBOX_GPS_SERVICE */
    public static final UUID SMARTCANTON_DEVBOX_GPS_SERVICE =
            UUID.fromString("10000000-AAAA-BBBB-CCCC-DDDDDDDDDDDD");

    public static final UUID SMARTCANTON_DEVBOX_GPS_POSITION =
            UUID.fromString("10000001-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_GPS_SPEED =
            UUID.fromString("10000002-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_GPS_COURSE =
            UUID.fromString("10000003-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_GPS_DATE =
            UUID.fromString("10000004-AAAA-BBBB-CCCC-DDDDDDDDDDDD");
    public static final UUID SMARTCANTON_DEVBOX_GPS_TIME =
            UUID.fromString("10000005-AAAA-BBBB-CCCC-DDDDDDDDDDDD");

}
