package com.master_hesso.smartcantonmanager.utils;

import java.util.UUID;

public class SmartCantonDevBoxBLEServices {

    /* SMARTCANTON_DEVBOX_LORA_SERVICE */
    public static final UUID SMARTCANTON_DEVBOX_LORA_SERVICE =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA00000000");

    public static final UUID SMARTCANTON_DEVBOX_LORA_APP_EUI =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA01000000");
    public static final UUID SMARTCANTON_DEVBOX_LORA_APP_KEY =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA02000000");
    public static final UUID SMARTCANTON_DEVBOX_LORA_DEVICE_EUI =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA03000000");
    public static final UUID SMARTCANTON_DEVBOX_LORA_LORA_CONFIRM_MODE =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA04000000");
    public static final UUID SMARTCANTON_DEVBOX_LORA_NETWORK_JOIN_STATUS =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA05000000");
    public static final UUID SMARTCANTON_DEVBOX_LORA_NETWORK_DEVICE_ADDRESS =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA06000000");
    public static final UUID SMARTCANTON_DEVBOX_LORA_NETWORK_NWTORK_SESSION_KEY =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA07000000");
    public static final UUID SMARTCANTON_DEVBOX_LORA_NETWORK_APP_SESSION_KEY =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA08000000");
    public static final UUID SMARTCANTON_DEVBOX_LORA_NETWORK_VALIDATE_NEW_CONFIGURATION =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA09000000");

    /* SMARTCANTON_DEVBOX_GPS_SERVICE */
    public static final UUID SMARTCANTON_DEVBOX_GPS_SERVICE =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA00000010");

    public static final UUID SMARTCANTON_DEVBOX_GPS_POSITION =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA01000010");
    public static final UUID SMARTCANTON_DEVBOX_GPS_SPEED =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA02000010");
    public static final UUID SMARTCANTON_DEVBOX_GPS_COURSE =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA03000010");
    public static final UUID SMARTCANTON_DEVBOX_GPS_DATE =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA04000010");
    public static final UUID SMARTCANTON_DEVBOX_GPS_TIME =
            UUID.fromString("DDDDDDDD-DDDD-CCCC-BBBB-AAAA05000010");

}
