PRIMARY_SERVICE(service_device_information, gBleSig_DeviceInformationService_d)
    CHARACTERISTIC(char_manufacturer_name_string, gBleSig_ManufacturerNameString_d, (gGattCharPropRead_c))
        VALUE_VARLEN(value_manufacturer_name_string, gBleSig_ManufacturerNameString_d, (gPermissionFlagReadable_c), 23, 3, "NXP")
    CHARACTERISTIC(char_model_number_string, gBleSig_ModelNumberString_d, (gGattCharPropRead_c))
        VALUE_VARLEN(value_model_number_string, gBleSig_ModelNumberString_d, (gPermissionFlagReadable_c), 23, 3, "NXP")
    CHARACTERISTIC(char_serial_number_string, gBleSig_SerialNumberString_d, (gGattCharPropRead_c))
        VALUE_VARLEN(value_serial_number_string, gBleSig_SerialNumberString_d, (gPermissionFlagReadable_c), 23, 3, "NXP")
    CHARACTERISTIC(char_hardware_revision_string, gBleSig_HardwareRevisionString_d, (gGattCharPropRead_c))
        VALUE_VARLEN(value_hardware_revision_string, gBleSig_HardwareRevisionString_d, (gPermissionFlagReadable_c), 23, 3, "NXP")
    CHARACTERISTIC(char_firmware_revision_string, gBleSig_FirmwareRevisionString_d, (gGattCharPropRead_c))
        VALUE_VARLEN(value_firmware_revision_string, gBleSig_FirmwareRevisionString_d, (gPermissionFlagReadable_c), 23, 3, "NXP")
    CHARACTERISTIC(char_software_revision_string, gBleSig_SoftwareRevisionString_d, (gGattCharPropRead_c))
        VALUE_VARLEN(value_software_revision_string, gBleSig_SoftwareRevisionString_d, (gPermissionFlagReadable_c), 23, 3, "NXP")
    CHARACTERISTIC(char_system_id, gBleSig_SystemId_d, (gGattCharPropRead_c))
        VALUE(value_system_id, gBleSig_SystemId_d, (gPermissionFlagReadable_c), 8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00)
    CHARACTERISTIC(char_ieee_1107320601_regulatory_certification_data_list, gBleSig_IeeeRcdl_d, (gGattCharPropRead_c))
        VALUE_VARLEN(value_ieee_1107320601_regulatory_certification_data_list, gBleSig_IeeeRcdl_d, (gPermissionFlagReadable_c), 23, 3, "NXP")
    CHARACTERISTIC(char_pnp_id, gBleSig_PnpId_d, (gGattCharPropRead_c))
        VALUE(value_pnp_id, gBleSig_PnpId_d, (gPermissionFlagReadable_c), 7, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00)

PRIMARY_SERVICE(service_heart_rate, gBleSig_HeartRateService_d)
    CHARACTERISTIC(char_heart_rate_measurement, gBleSig_HrMeasurement_d, (gGattCharPropNotify_c))
        VALUE_VARLEN(value_heart_rate_measurement, gBleSig_HrMeasurement_d, (gPermissionNone_c), 22, 2, 0x00, 0xB4)
        CCCD(cccd_heart_rate_measurement)
    CHARACTERISTIC(char_body_sensor_location, gBleSig_BodySensorLocation_d, (gGattCharPropRead_c))
        VALUE(value_body_sensor_location, gBleSig_BodySensorLocation_d, (gPermissionFlagReadable_c), 1, 0x00)
    CHARACTERISTIC(char_heart_rate_control_point, gBleSig_HrControlPoint_d, (gGattCharPropWrite_c))
        VALUE(value_heart_rate_control_point, gBleSig_HrControlPoint_d, (gPermissionFlagWritable_c), 1, 0x00)

PRIMARY_SERVICE(service_battery, gBleSig_BatteryService_d)
    CHARACTERISTIC(char_battery_level, gBleSig_BatteryLevel_d, (gGattCharPropNotify_c | gGattCharPropRead_c))
        VALUE(value_battery_level, gBleSig_BatteryLevel_d, (gPermissionFlagReadable_c), 1, 0x00)
        DESCRIPTOR(descriptor_battery_level, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00)
        CCCD(cccd_battery_level)

PRIMARY_SERVICE(service_generic_attribute, gBleSig_GenericAttributeProfile_d)
    CHARACTERISTIC(char_service_changed, gBleSig_GattServiceChanged_d, (gGattCharPropIndicate_c))
        VALUE(value_service_changed, gBleSig_GattServiceChanged_d, (gPermissionNone_c), 4, 0x00, 0x00, 0x00, 0x00)
        CCCD(cccd_service_changed)

PRIMARY_SERVICE(service_generic_access, gBleSig_GenericAccessProfile_d)
    CHARACTERISTIC(char_device_name, gBleSig_GapDeviceName_d, (gGattCharPropRead_c | gGattCharPropWrite_c))
        VALUE_VARLEN(value_device_name, gBleSig_GapDeviceName_d, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 23, 17, "SmartCantonDevBox")
    CHARACTERISTIC(char_appearance, gBleSig_GapAppearance_d, (gGattCharPropRead_c))
        VALUE(value_appearance, gBleSig_GapAppearance_d, (gPermissionFlagReadable_c), 2, UuidArray(gUnknown_c))
//    CHARACTERISTIC(char_peripheral_privacy_flag, gBleSig_GapPeripheralPrivacyFlag_d, (gGattCharPropRead_c))
//        VALUE(value_peripheral_privacy_flag, gBleSig_GapPeripheralPrivacyFlag_d, (gPermissionFlagReadable_c), 1, 0x00)
//    CHARACTERISTIC(char_reconnection_address, gBleSig_GapReconnectionAddress_d, (gGattCharPropWrite_c))
//        VALUE(value_reconnection_address, gBleSig_GapReconnectionAddress_d, (gPermissionFlagWritable_c), 6, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00)
    CHARACTERISTIC(char_peripheral_preferred_connection_parameters, gBleSig_GapPpcp_d, (gGattCharPropRead_c))
        VALUE(value_peripheral_preferred_connection_parameters, gBleSig_GapPpcp_d, (gPermissionFlagReadable_c), 8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00)

PRIMARY_SERVICE_UUID128(service_smartcanton_devbox, uuid_service_smartcanton_devbox)
    CHARACTERISTIC_UUID128(char_lora_app_eui, uuid_lora_app_eui, (gGattCharPropRead_c | gGattCharPropWrite_c))
        VALUE_UUID128_VARLEN(value_lora_app_eui, uuid_lora_app_eui, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 23, 3, "NXP")
//        DESCRIPTOR(descriptor_lora_app_eui, 0x2901, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 23, 3, "NXP")
    CHARACTERISTIC_UUID128(char_lora_app_key, uuid_lora_app_key, (gGattCharPropRead_c | gGattCharPropWrite_c))
        VALUE_UUID128_VARLEN(value_lora_app_key, uuid_lora_app_key, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 23, 3, "NXP")

PRIMARY_SERVICE_UUID128(service_potentiometer, uuid_service_potentiometer)
	CHARACTERISTIC_UUID128(char_potentiometer_relative_value, uuid_characteristic_potentiometer_relative_value, (gGattCharPropRead_c | gGattCharPropNotify_c))
		VALUE_UUID128(value_potentiometer_relative_value, uuid_characteristic_potentiometer_relative_value, (gPermissionFlagReadable_c ), 1, 0x00)
		CCCD(cccd_potentiometer)
		//DESCRIPTOR(cpfd_potentiometer, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, gCpfdUnsigned8BitInteger, 0x00,0xAD,0x27,0x01, 0x00, 0x00)
		DESCRIPTOR(cpfd_potentiometer, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x04, 0x00, 0xAD, 0x27, 0x01, 0x00, 0x00)
